apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: seaweedfs
  name: seaweedfs
spec:
  replicas: {{ .Values.seaweedfs.replicas }}
  selector:
    matchLabels:
      service: seaweedfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: seaweedfs
    spec:
      containers:
        - args:
            - server
            - -s3
            - -dir=/data
          image: {{ .Values.images.seaweedfs }}
          name: seaweedfs
          ports:
            - containerPort: 8333
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: seaweedfs-data
      restartPolicy: Always
      volumes:
        - name: seaweedfs-data
          persistentVolumeClaim:
            claimName: seaweedfs-data
status: {}
---
{{- if ne (int .Values.seaweedfs.replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: seaweedfs
  name: seaweedfs
spec:
  ports:
    - name: "8333"
      port: 8333
      targetPort: 8333
  selector:
    service: seaweedfs
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: seaweedfs-data
  name: seaweedfs-data
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.seaweedfs.size | quote }}
  storageClassName: {{ .Values.pvc.seaweedfs.storageClassName }}
status: {}
{{- end -}}