ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: anteon.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  name: nginx-service
  port: 80
  nodePort: 30000
  replicas: 1

influxDB:
  # If you set external to true, this means that you will manage the influxdb server yourself
  # Recommended influxDB version: 2.6.1
  # You must set url, apiToken and org
  # and you must create the buckets manually:
  #   - hammerBucket
  #   - hammerBucketDetailed
  #   - hammerBucketIteration
  # username and password are only used if external is false
  external: false
  url: "http://influxdb:8086"
  apiToken: "5yR2qD5zCqqvjwCKKXojnPviQaB87w9JcGweVChXkhWRL"
  org: "ddosify"
  username: "admin" # only used if external is false
  password: "ChangeMe" # only used if external is false
  initBucketName: "hammerBucket"
  initMode: "setup"
  replicas: 1

postgres:
  # If you set external to true, this means that you will manage the postgres server yourself
  # Recommended postgres version: 16.2
  # You must set host, port, username and password
  # and you must create the databases manually
  #   - backend
  #   - hammermanager
  external: false
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "ChangeMe"
  replicas: 1

pvc:
  influxDB:
    storageClassName: ""
    size: 5Gi
  postgres:
    storageClassName: ""
    size: 50Gi
  seaweedfs:
    storageClassName: ""
    size: 30Gi

alazBackend:
  replicas: 3
  celeryBeatReplicas: 1
  celeryWorkerReplicas: 2

backend:
  replicas: 3
  celeryBeatReplicas: 1
  celeryWorkerReplicas: 1
  # The defaultMonitoringID is used to create a default cluster with defaultClusterName with the specified monitoring ID.
  # If the defaultMonitoringID is not provided, no default cluster will be created.
  # defaultMonitoringID format is uuid
  defaultMonitoringID: ""
  
  # The defaultClusterName is used to create a cluster with the specified name after the self-hosted setup.
  # If the defaultMonitoringID is not provided, no default cluster will be created.
  defaultClusterName: "default-cluster"

frontend:
  replicas: 1

hammer:
  replicas: 1

hammerdebug:
  replicas: 1

hammermanager:
  replicas: 1
  celeryBeatReplicas: 1
  celeryWorkerReplicas: 1

prometheus:
  replicas: 1

rabbitmq:
  replicas: 1

redisBackend:
  replicas: 1

redisAlazBackend:
  replicas: 1

seaweedfs:
  replicas: 1

images:
  alazBackend: ddosify/selfhosted_alaz_backend:2.3.5
  backend: ddosify/selfhosted_backend:3.2.9
  frontend: ddosify/selfhosted_frontend:4.1.2
  hammer: ddosify/selfhosted_hammer:2.0.0
  hammermanager: ddosify/selfhosted_hammermanager:2.0.2
  influxdb: influxdb:2.6.1-alpine
  nginx: nginx:1.25.5-alpine
  postgres: postgres:16.2-alpine
  prometheus: prom/prometheus:v2.37.9
  rabbitmq: rabbitmq:3.13.1-alpine
  redis: redis:7.2.4-alpine
  seaweedfs: chrislusf/seaweedfs:3.64
  initContainerBusybox: busybox:1.36.1
