name: Documentation

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  link-checker:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check the links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --max-concurrency 1 -v *.md **/**/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spelling-checker:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check spelling mistakes
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          path: "*.md **/**/*.md"
